name = "DynamicBoundsBase"
uuid = "890bb398-7f8e-4565-ac8e-279ab2833f68"
authors = ["Matthew Wilhelm <matthew.wilhelm@uconn.edu>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
DocStringExtensions = "~0.8"
Reexport = "~0.2"
