name = "DynamicBoundsBase"
uuid = "890bb398-7f8e-4565-ac8e-279ab2833f68"
authors = ["Matthew Wilhelm <matthew.wilhelm@uconn.edu>"]
version = "0.6"

[deps]
DiffEqSensitivity = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
DiffEqSensitivity = "~6"
DocStringExtensions = "~0.8"
ElasticArrays = "~1"
ForwardDiff = "~0.10"
Reexport = "~0.2"
SciMLBase = "~1"
julia = "~1.6, ~1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
