name = "DynamicBoundsBase"
uuid = "890bb398-7f8e-4565-ac8e-279ab2833f68"
authors = ["Matthew Wilhelm <matthew.wilhelm@uconn.edu>"]
version = "0.3.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
DiffEqBase = "6.12.2"
DocStringExtensions = "~0.8"
Reexport = "~0.2"
julia = "~1.2, ~1.3, ~1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
